// Generated by CoffeeScript 2.0.1
(function() {
  var a, b, sum;

  sum = function(a, b) {
    return a + b;
  };

  a = +prompt("enter number a");

  b = +prompt("enter number b");

  console.log(sum(a, b));

}).call(this);
