// Generated by CoffeeScript 2.0.1
(function() {
  //ЗАДАНИЕ 1
  var a, b, sum, today, weekday;

  sum = function(a, b) {
    return a + b;
  };

  //ЗАДАНИЕ 2
  weekday = function(date) {
    var WEEKDAYS, day;
    WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    day = date.getDay();
    return WEEKDAYS[day - 1];
  };

  //ТЕСТ ЗАДАНИЯ 1
  a = +prompt("enter number a");

  b = +prompt("enter number b");

  alert(`Сумма будет = ${sum(a, b)}`);

  //ТЕСТ ЗАДАНИЯ 2
  today = new Date;

  alert(`Сегодня: ${today}, а день недели ${weekday(today)}`);

}).call(this);
